### ISSUE TITLE
Using wall_s=1.0 and a custom SOL definition with split_chamber=False does not merge the plasma and SOL

### ISSUE THREAD

**Issue by Edgar-21** [svalinn/parastell#144]
Expected behavior is to get one volume representing the SOL combined with the plasma.

**Comment by connoramoreno** [comment]
Edgar and I resolved this, but for future reference, to have the `"chamber"` volume be offset from the plasma by a given thickness matrix when `split_chamber = False`, include an item in the radial build with the key `"chamber"` and desired `"thickness_matrix"` value. Including a radial build item with a `"sol"` key will create a separate "sol" component. We can consider adding a warning about this.
