### ISSUE TITLE
Version of Coreform Cubit for exporting DAGMC

### ISSUE THREAD

**Issue by rmchurch** [svalinn/parastell#20]
What version of Coreform Cubit is intended to be used? Using 2023.11 on Linux, it does not seem to have 'export dagmc'. It has 'export cf_dagmc', but for some reason even when updating to use that, it errors out in the call in cubit_export

**Comment by pshriwise** [comment]
As for why the `export cf_dagmc` command is failing, I'm unsure. I encountered a problem like this when trying to export a DAGMC file with a working directory of `/`, but that was on a Mac so the cause may not be (and likely isn't) the same here.

**Comment by pshriwise** [comment]
Hi @rmchurch, that's correct. Coreform now supports a DAGMC export format via the `export cf_dagmc` command. In this command, the exported facets come from the surface trimesher that is part of Cubit's proper meshing engine (as opposed to the graphics facets used by the Svalinn DAGMC plugin). Also, yes, this meshing scheme is going to use different parameters. I'm working with them currently on adding parameters along with some diagnostics of the resulting trimesh that are significant for particle transport.

**Comment by Edgar-21** [comment]
Did you get it working? If not, can you post the error message from cubit_export please? And the script you are using to build the geometry? I have had issues with the cubit export in the past

**Comment by rmchurch** [comment]
OK, I did get these working with both. I'll try to summarize here:

1. `export dagmc ...`
The issue I had here was getting the plugin to work. I am on a RHEL machine, so none of the packaged plugin builds would work. At first I tried to build the plugin directly, but ran into issues with which versions of MOAB and DAGMC [(GH issue here](https://github.com/svalinn/Cubit-plugin/issues/154#issuecomment-1899779190), I didn't resolve this, I think there was a breaking change in `ProgOpts` call (2 strings instead of 1), but didn't dig enough to figure out). I saw that with Coreform Cubit 2023.8 it started shipping the svalinn cubit plugin, and I tried to use as instructed by @pshriwise , but for some reason `export dagmc ...` still wasn't working in `parastell`. I finally figured out that I had to additionally set an env variable `export CUBIT_PLUGIN_DIR=...` to the path of the plugin folder, and after that it worked. However, for the model I put in, it took a long time to generate the mesh (4+ hours), and convert to .vtk (another 4+ hours), which I realized later was the tolerances I had from the default (this is a rather large machine also, `R0~9.6 m`). I have defined from default example:
```
    'facet_tol': 1,
    'len_tol': 5,
    'norm_tol': None,
```
So I can play around with them and work to get a more manageable mesh.
![image](https://github.com/svalinn/parastell/assets/1577108/8647effb-db6d-4ed0-a3a6-165827dc0619)

2. `export cf_dagmc...`
The issue here that I had was I was trying to use it as a drop-in replacement for the plugin `export dagmc...`, wherein reality its a different workflow now, you have to mesh first before exporting (I guess svalinn plugin does the meshing for you upon export?). This [link](https://forum.coreform.com/t/coreform-dagmc-model-preparation-and-export-tutorial/2073) shows kind of the methodology. I was also given some code from Coreform because the trimeshing of the magnets since spline-like was difficult, and they suggested meshing using quadrilaterals then converting to triangular mesh. 
```
set trimesher coarse on ratio 100 angle 5
surface all in volume 1 to 8 scheme trimesh
mesh surface all in volume 1 to 8
surface all in volume 9 to 28 size 5
mesh surface all in volume 9 to 28
qtri surface all in volume 9 to 28
```
This gave a very fine mesh on the magnets and coarser on the other components
![image](https://github.com/svalinn/parastell/assets/1577108/7641a41d-d1d8-4396-9a33-34c4845e7ca3)

I am curious for the future of the svalinn dagmc plugin, will it eventually merge with the Coreform effort, or are the different workflows distinct enough that it will be kept separate?

**Comment by gonuke** [comment]
Thanks for all the details @rmchurch  - we definitely need to update/refine our documentation for some of these things. 
 We also just merged a PR to tackle one of the issues.

Coreform has taken over the development and maintenance of both workflows.  They have integrated the Svalinn workflow into Cubit and subsequently developed their own workflow.

FWIW, the difference comes down to which engine generates the surface mesh.  The Svalinn workflow relies on the underlying solid modeling engine to generate facets as it would for visualization.  The Coreform workflow relies on their mesh generation expertise.  Given the better control offered by the latter, my best hunch is that it will emerge as the preferred workflow.
