### ISSUE TITLE
mamba install -c conda-forge moab doesn't install pymoab

### ISSUE THREAD

**Issue by Fuad-HH** [svalinn/parastell#36]
I am trying to install parastell on a rhel7 machine. I followed the installation instructions given in the README but I got the error that pymoab is not recognized. I tried to install specific versions and builds too but none of them are installing pymoab although they are installing moab package without any issue. Then I built moab myself with pymoab from source and I was able to get pymoab in the parastell_env I created. But when I tried to run ExampleScript.py it was complaining that it needed module sklearn and imp. I tried to install importlib but it is not compatible with python 3.12 which is also mentioned in[ this post](https://stackoverflow.com/questions/77274572/multiqc-modulenotfounderror-no-module-named-imp).
Could you please give me the updated installation instructions?

**Comment by Edgar-21** [comment]
I just posted a yml file for my currently working conda environment on #37 , it might work for you, sorry about the install issues

**Comment by connoramoreno** [comment]
Addressed in solution to Issue #37
