### ISSUE TITLE
Refactor use of filaments for magnet coils

### ISSUE THREAD

**Issue by gonuke** [svalinn/parastell#47]
Instead of reading and storing all the filament data in the `MagnetSet` class, use each filament data to initialize a new `MagnetCoil` object as it becomes available.

Also store all of the filament points in the `MagnetCoil` class and only filter to fewer data points when building the curves.

This will then also require a refactor of how we decide which magnets are in the toroidal extent, perhaps with a method on the `MagnetCoil` class that returns a Boolean if it is/is not.

**Comment by connoramoreno** [comment]
We might reconsider this issue in the context of the modified magnet modeling workflow. I think it's still worth doing, but may look differently in that new context.

**Comment by gonuke** [comment]
I think still makes sense, the filament data should be a member of the coil rather than the set
