### ISSUE TITLE
Facilitate user defined reaction rates

### ISSUE THREAD

**Issue by gonuke** [svalinn/parastell#51]
Source mesh currently has hard-coded reaction rates that assume:
* relationship between ion temperature and plasma parameter s
* relationship between ion density and plasma parameter s
* DT fusion reaction rates based on ion temperature and density

Users need to provide a mechanism for defining their own relationship between ion temperature and density as a function of the plasma parameter, s.  Users may also want to use a different fusion reaction rate formula, either by selecting the fuel and we provide some standard rate as a function of T, n, or an even more flexible approach.

**Comment by connoramoreno** [comment]
Has this been addressed?

**Comment by gonuke** [comment]
Closed by #129
