### ISSUE TITLE
Review structure of YAML file

### ISSUE THREAD

**Issue by gonuke** [svalinn/parastell#52]
Consider improvements in yaml file structure to reduce redundancy and/or opportunities for inconsistency

**Comment by connoramoreno** [comment]
May or may not have been addressed in #56. I'll suspend closing this issue until confirmation by @gonuke

**Comment by gonuke** [comment]
I think we might have done this once, but maybe we should look at a sample YAML file during a meeting to see if we all agree to the structure and whether it can be made any better.

**Comment by connoramoreno** [comment]
Sounds good!

**Comment by connoramoreno** [comment]
Closed via #70
