### ISSUE TITLE
Integration with Updated PyStell-UW

### ISSUE THREAD

**Issue by connoramoreno** [svalinn/parastell#72]
ParaStell will need to update its integration with [PyStell-UW](https://github.com/aaroncbader/pystell_uw), as a new update to the `master` branch of PyStell-UW changes its syntax.

The version of `read_vmec.py` currently used in ParaStell corresponds to the `old` branch of PyStell-UW. ParaStell will not work for users installing the `master` branch of PyStell-UW.

**Comment by gonuke** [comment]
Does this change only installation or also how we import/use it?

**Comment by connoramoreno** [comment]
Both

**Comment by connoramoreno** [comment]
It's a minor change for use but a change to syntax nonetheless

**Comment by connoramoreno** [comment]
There are several issues with the updated branch of PyStell-UW so for the time being, I am going to create updated installation documentation for the `main` and `oo_version` branches that refer users to the `old` branch of PyStell-UW
