### ISSUE TITLE
Source mesh connectivity

### ISSUE THREAD

**Issue by gonuke** [svalinn/parastell#8]
The source mesh is topologically a torus.  In the current implementation, two sets of vertices are created at phi = 0 = 2 * pi and/or theta = 0 = 2 * pi.  In addition to a minor concern on memory usage, it results in a mesh that does have logical connectivity across the phi = 0 = 2 * pi or theta = 0 = 2 * pi boundary.  This is not a problem, in practice, for source meshes since each mesh element gets sampled independently and connectivity is not relevant.  

If this mesh generation approach is used for other purposes in the future, it may be an issue for uses in which connectivity is important.

We should consider an improvement that reuses vertices on the phi/theta = 0 = 2*pi boundaries.

**Comment by connoramoreno** [comment]
Handled in PR #9

**Comment by connoramoreno** [comment]
Closing this as the corresponding PR has been merged.
